# The URL the site will be built for
base_url = "https://salorak.es"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

author = "Sal O'Rak"
theme = "apollo"

taxonomies = [
    { name = "tags"},
    { name = "authors"},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

render_emoji=true

bottom_footnotes=true


[extra]
theme = "dark"

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/hector-alarcon-salorak/", icon = "linkedin" },
    { name = "github", url = "https://github.com/salorak/", icon = "github" },
]

menu = [
    { name = " /home ", url = "/", weight = 0, desc = "Homepage, exactly where you are."},
    { name = " /blog ", url = "/blog/", weight = 1, desc = "Posts like a blog. Thoughts, works and working articles."},
    { name = " /projects ", url = "/projects/", weight = 2, desc = "Projects I've developed or contributed to. Sometimes, projects I'd love to contribute to."},
    { name = " /about ", url = "/about/", weight = 3, desc = "If you want to know more about me, who I am and what I do, this is the place." },
]

stylesheets = [
    "theme.css",
    "custom.css",
    "projects.css"
]

logo = "/images/minimalist-logo_128x128.png"
favicon = "/icon/favicon.svg"

toc = true

use_cdn = false
fancy_code = true
insert_anchor_links = "heading"

last_page = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"


